image: limaofeng/gradle-alpine

before_script:
  - export LANG="zh_CN.UTF-8"
  - cp -rf .gradle ~/.gradle
#  - echo 10.45.21.126 maven.zbsg.com.cn >> /etc/hosts

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test

sonar:
  stage: test
  script:
    - gradle sonar -x test
  only:
    - tags

deploy:
  stage: deploy
  script:
      - gradle upload -x test
  only:
    - tags